#!/usr/bin/env bash

RESET="\e[0m"
GREEN="\e[42m"
YELLOW="\e[43m"
DEFAULT="\e[49m"

main() {
    echo "welcome to shwordle!"

    while true; do
        echo
        echo "Menu:"
        echo "1) Play"
        echo "2) Exit"

        read -p "Choose an option: " choice
        case "${choice}" in
            1)
                play
                ;;
            2)
                echo $'\nThanks for playing!'
                echo "Made by ahmadnaufalhakim"
                break
                ;;
            *)
                echo "Invalid choice! Please enter 1 or 2."
                ;;
        esac
    done
}

check() {
    target="$1"
    guess="$2"

    result=( "" "" "" "" "" )

    # Pass 1: greens
    for (( i=0; i<5; i++ )); do
        if [[ "${guess:i:1}" == "${target:i:1}" ]]; then
            result[$i]="${GREEN}${guess:i:1}"
            (( count["${guess:i:1}"]-- ))
        fi
    done

    # Pass 2: yellows & grays
    for (( i=0; i<5; i++ )); do
        if [[ -z "${result[$i]}" ]]; then
            letter="${guess:i:1}"
            if (( count["$letter"] > 0 )); then
                result[$i]="${YELLOW}${guess:i:1}"
                (( count["$letter"]-- ))
            else
                result[$i]="${DEFAULT}${guess:i:1}"
            fi
        fi
    done

    IFS=""
    printf '%b\n' "${result[*]}${RESET}"
}

play() {
    clear
    target="${words[RANDOM % ${#words[@]}]}"
    declare -A count
    for (( i=0; i<5; i++ )); do
        (( count["${target:i:1}"]++ ))
    done

    local attempts=1
    while (( attempts <= 6 )); do
        read -p "Guess #${attempts}: " guess
        check "${target}" "${guess}"
        if [[ "${guess}" == "${target}" ]]; then
            echo "correct! you win! wow"
            return
        else
            echo "wrong! try again"
        fi
        (( attempts++ ))
    done

    echo "out of attempts! the word was: ${target}"
}

read -r -d '' WORD_LIST <<'EOM'
ABCDE
FGHIJ
KLMNO
PQRST
UVWXY
ZZ
EOM
mapfile -t words <<< "${WORD_LIST}"

main
