#!/usr/bin/env bash

main() {
    echo "welcome to shwordle!"

    while true; do
        echo
        echo "Menu:"
        echo "1) Play"
        echo "2) Exit"

        read -p "Choose an option: " choice
        case "${choice}" in
            1)
                play
                ;;
            2)
                echo $'\nThanks for playing!'
                echo "Made by ahmadnaufalhakim"
                break
                ;;
            *)
                echo "Invalid choice! Please enter 1 or 2."
                ;;
        esac
    done
}

play() {
    clear
    local target="${words[RANDOM % ${#words[@]}]}"
    local attempts=1

    while (( attempts <= 6 )); do
        read -p "Guess #${attempts}: " guess
        if [[ "${guess}" == "${target}" ]]; then
            echo "correct! you win! wow"
            return
        else
            echo "wrong! try again"
        fi
        (( attempts++ ))
    done

    echo "out of attempts! the word was: ${target}"
}

read -r -d '' WORD_LIST <<'EOM'
ABCDE
FGHIJ
KLMNO
PQRST
UVWXY
Z
EOM
mapfile -t words <<< "${WORD_LIST}"

main
